function LanguageControllerEN()
{
	this.language = {
		buttons : {
			"dialCallBtn" : "dialCall",
			"appSendMsgToUCBtn" : "appSendMsgToUC",
			"createConfBtn" : "Schedule Conference"
		},

		titles : {
			"descriptionUC" : "This Demo contains eSDK UC functions.",
			"copyright" : "Copyright © Huawei Technologies Co., Ltd. 1998-2014. All rights reserved.",
			"description" : "Description",
			"exection" : "Execution",
			"sourceCode" : "Source Code",
			"inputParam" : "input:",
			"outputParam" : "output:",
			"resultCode" : "resultCode:",
			"inputParameterDesc" : "input parameters description:",
			"outputParameterDesc" : "output parameters description:",
			"inputParameterTd" : "parameter",
			"inputTypeTd" : "type",
			"inputRestrictionTd" : "restriction",
			"inputDescriptionTd" : "description",
			"outputParameterTd" : "parameter",
			"outputTypeTd" : "type",
			"outputRestrictionTd" : "restriction",
			"outputDescriptionTd" : "description",
			"resultCodeTd" : "for successful return zero, and failed return other codes",
			"operationSuccess" : "operation success",
			"operationFailed" : "operation failed",
			"reserveTd32" : "Reserved field<br>The maximum length is 32 bytes",
			"reserveTd64" : "Reserved field<br>The maximum length is 64 bytes",
			
			
			"ucTree_1_span" : "Typical functions",
			"ucTree_2_span" : "CTD",
			"ucTree_3_span" : "dialCall",
			"ucTree_4_span" : "IM",
			"ucTree_5_span" : "appSendMsgToUC",
			"ucTree_6_span" : "Conference",
			"ucTree_7_span" : "createConf",
			
			"ucTree_1_span_tag" : "",
			"ucTree_2_span_tag" : "",
			"ucTree_3_span_tag" : "",
			
			"interfaceName" : "interfaceName",
			"interfaceFunction" : "interfaceFunction",
			
			"dialCallInterface" : "Function Name：dialCall<br/>",
			"dialCallDesc" : "CTD call",
			"initiatorLabel" : "initiator:",
			"callerLabel" : "caller:",
			"calleeLabel" : "callee:",
			"callIdLabel" : "call Id:",
			"initiatorInputTd" : "initiator：<br>UC账号：格式为UC:UC帐号，如UC:j00213891 <br>应用账号：格式为APP:appid，如APP:000011112512（暂不支持）",
			"callerInputTd" : "主叫号码<br>说明：支持UC号码、手机号码、电话号码三种形式。其中，手机号码、电话号码必须是E.164格式（国际公共电话号码方案，格式为：国家码+国内目的码+用户号码，如：+86-10-62618501）。",
			"calleeInputTd" : "被叫号码<br>说明：支持UC号码、手机号码、电话号码三种形式。其中，手机号码、电话号码必须是E.164格式（国际公共电话号码方案，格式为：国家码+国内目的码+用户号码，如：+86-10-62618501）。",
			"callIdOutputTd" : "call Id",
			
			"initiatorNull" : "initiator can not be null",
			"alarmEventIdNotNumber" : "caller can not be null",
			"calleeNull" : "callee can not be null",
			
			"appSendMsgToUCInterface" : "Function Name：appSendMsgToUC <br/>",
			"appSendMsgToUCDesc" : "Send message",
			"sendNumberLabel" : "Send Number:", 
			"ucAccountLabel" : "UC Account:", 
			"messageLabel" : "Message:", 
			"messageAttention": "注：此处的消息文需经过Base64编码处理。<br/>例如：消息'&lt;imbody&gt;&lt;content&gt;Hellow World!&lt;/content&gt;&lt;/imbody&gt;'经过Base64处理后为<br/>'PGltYm9keT48Y29udGVudD5IZWxsb3cgV29yb<br/>GQhPC9jb250ZW50PjwvaW1ib2R5Pg=='。",
			"sendNumberInputTd" : "即时消息接入码<br>例如：“99991234”，该值在BME中的OBG应用管理配置项，用户开户时配置。",
			"ucAccountInputTd" : "uc account",
			"messageInputTd" : "message (Base64编码)<br>消息内容的格式为：&lt;imbody&gt;&lt;content&gt;内容&lt;/content&gt;&lt;/imbody&gt;",
			
			"sendNumberNull" : "send number can not be null",
			"ucAccountNull" : "uc account can not be null",
			"ucMessageNull" : "message can not be null",
			
			"createConfInterface" : "Function Name：createConf(Schedule Conference)<br/>",
			"createConfDesc" : "Schedule conference",
			"confInfoInputTd" : "Conference Parameter",
			"confTypeInputTd" : "Conference Type:<br> 1：即时会议<br>2：预约会议 <br>3：需要预留多媒体资源的即时会议 <br>4：需要预留多媒体资源的预约会议 ",
			"confSubjectInputTd" : "Conference Topic",
			"initiatorConfInputTd" : "Initiator UC Account",
			"beginTimeInputTd" : "Begin Time(如果是即时会议，该属性无效)",
			"endTimeInputTd" : "End Time(如果是即时会议，该属性无效)",
			"conferenceParamLabel" : "Schedule Conference",
			"ConfUserInputTd" : "Chairman",
			"ConfUsersInputTd" : "Attendee:<br>说明：即时会议（confType=1，3），不支持此字段。会议发起方在收到主持人与会成功的通知后，再调用添加与会者接口addIntoConf增加会议成员。",
			"mediaTypeInputTd" : "Media Type:会议媒体类型（二进制表示，特定位置为1表示开通该功能，0表示未开通该功能）：<br>第一位：音频<br>第二位：视频<br>第三位：数据<br>说明:会议媒体类型可以进行组合，如111表示会议媒体类型为音视频加数据，100表示会议媒体类型为音频。目前仅支持100和111。",
			"chairmanPasswordInputTd" : "Chairman Password<br>说明：密码长度默认为9位或9位以上，且不能同UC系统中已预约的会议密码相同。（即时会议暂不支持）。",
			"memberPasswordInputTd" : "Member Password<br>说明：密码长度默认为9位或9位以上，且不能同UC系统中已预约的会议密码相同。（即时会议暂不支持）。",
			"maxAttendeeInputTd" : "Max Attendee Number，最大与会人数可以在数据库中配置，默认为480人以内",
			"confUserNumberInputTd" : "Attendee User Number，支持UC号码、手机号码、区号+固定电话号码",
			"confUserNameInputTd" : "Attendee User Name",
			"confUserAccountInputTd" : "Attendee User UC Account",
			"confUserTalkModeInputTd" : "Talk Mode:<br>0：无发话权<br>1：有发话权<br>2：正在申请",
			"confUserStatusInputTd" : "Attendee Status:<br>1：正在邀请<br>2：邀请成功<br>3：邀请失败<br>4：挂断",	
			"isSupportVideoInputTd" : "Support Video:<br>0：支持<br>1：不支持",
			"confUserRoleInputTd" : "Attendee Role:<br>1：主持人<br>2：普通成员",
			"confUserEmailInputTd" : "Email，eg.zhangsan@huawei.com",
			"confIdOutputTd" : "Conference Id",
			"confIdLabel" : "conference Id:",
			"confTypeLabel" : "Conference Type：",
			"confTypeOption1" : "即时会议",
			"confTypeOption2" : "预约会议",
			"confTypeOption3" : "需要预留多媒体资源的即时会议",
			"confTypeOption4" : "需要预留多媒体资源的预约会议",
			"subjectLabel" : "Conference Topic:",
			"confInitiatorLabel" : "Initiator UC Account:",
			"confBeginTimeLabel" : "Begin Time(yyyy/mm/dd hh:mm)：",
			"confEndTimeLabel" : "End Time(yyyy/mm/dd hh:mm)：",
			"chairmanNumberLabel" : "Chairman Number:",
			"chairmanNameLabel" : "Chairman Name:",
			"chairmanAccountLabel" : "Chairman Account:",
			"chairmanTalkModeLabel" : "Chairman Talk Mode:",
			"chairmanStatusLabel" : "Chairman Status:",
			"chairmanSupportVideoLabel" : "Support Video:",
			"chairmanRoleLabel" : "Chairman Role:",
			"chairmanEmailLabel" : "Email：",
			"mediaTypeLabel" : "Media Type:",
			"chairmanPasswordLabel" : "Chairman Password:",
			"memberPasswordLabel" : "Member Password:",
			"maxAttendeeLabel" : "Max Attendee:",
			
			
			"TalkMode0" : "无发话权",
			"TalkMode1" : "有发话权",
			"TalkMode2" : "正在申请",
			
			"statusOption1" : "正在邀请",
			"statusOption2" : "邀请成功",
			"statusOption3" : "邀请失败",
			"statusOption4" : "挂断",
			
			"supportVideoOption0" : "支持",
			"supportVideoOption1" : "不支持",
			
			"roleOption1" : "主持人",
			"roleOption2" : "普通成员",
			
			"mediaTypeSpan1" : "音频",
			"mediaTypeSpan2" : "视频",
			"mediaTypeSpan3" : "数据",
			
			"confUserNumberErrTip" : "与会者号码不能为空",
			"subjectErrTip" : "会议主题不能为空",
			"initiatorErrTip" : "会议发起者的账号不能为空",
			"chairmanNumberErrTip" : "主席号码不能为空",
			"maxAttendeeNullErrTip" : "最大与会者人数不能为空",
			"chairmanEmailErrTip" : "主席Email格式不正确",
			"confUserEmailErrTip" : "与会者Email格式不正确",
			"maxAttendeeErrTip" : "最大与会者人数只能为数字",
			"confBeginTimeErrTip" : "时间格式为：yyyy/mm/dd hh:mm,例如：2014/02/13 08:30",
			"confEndTimeErrTip" : "时间格式为：yyyy/mm/dd hh:mm,例如：2014/02/13 08:30",
			
			"confUserParamBtn" : "Add Attendee",
			"confUserNumberLabel" : "Attendee Num",
			"confUserNameLabel" : "Attendee Name",
			"confUserAccountLabel" : "Account",
			"confUserTalkModeLabel" : "Talk Mode",
			"confUserStatusLabel" : "Status",
			"confUserSupportVideoLabel" : "Support Video",
			"confUserRoleLabel" : "Role",
			"confUserEmailLabel" : "Email",
			"confUserOptionLabel" : "Option"
		}
	};
}