function LanguageControllerZH()
{
	this.language = {
		buttons : {
			"dialCallBtn" : "发起CTD呼叫",
			"appSendMsgToUCBtn" : "向UC用户发送消息",
			"createConfBtn" : "发起会议"
		},

		titles : {
			"descriptionUC" : "此Demo包含了UC三个接口的使用示例：dialCall(发起CTD呼叫)，appSendMsgToUC(向UC用户发送消息)，createConf(发起会议)",
			"copyright" : "版权所有 © 华为技术有限公司 1998-2014。 保留一切权利。粤A2-20044005号",
			"description" : "说明",
			"exection" : "执行",
			"sourceCode" : "源码",
			"inputParam" : "输入:",
			"outputParam" : "输出:",
			"resultCode" : "结果码:",
			"inputParameterDesc" : "输入参数描述:",
			"outputParameterDesc" : "返回参数描述:",
			"inputParameterTd" : "参数",
			"inputTypeTd" : "类型",
			"inputRestrictionTd" : "约束",
			"inputDescriptionTd" : "描述",
			"outputParameterTd" : "参数",
			"outputTypeTd" : "类型",
			"outputRestrictionTd" : "约束",
			"outputDescriptionTd" : "描述",
			"resultCodeTd" : "成功返回0，失败返回错误码",
			"operationSuccess" : "操作成功",
			"operationFailed" : "操作失败",
			"reserveTd32" : "保留字段<br>长度限制32字节",
			"reserveTd64" : "保留字段<br>长度限制64字节",
			
			"ucTree_1_span" : "典型功能",
			"ucTree_2_span" : "CTD呼叫管理",
			"ucTree_3_span" : "dialCall",
			"ucTree_4_span" : "应用即时消息",
			"ucTree_5_span" : "appSendMsgToUC",
			"ucTree_6_span" : "会议管理",
			"ucTree_7_span" : "createConf",
			
			"ucTree_1_span_tag" : "发起CTD呼叫",
			"ucTree_2_span_tag" : "向UC用户发送消息",
			"ucTree_3_span_tag" : "创建会议",
			
			"interfaceName" : "接口名称",
			"interfaceFunction" : "接口功能",			
			
			"dialCallInterface" : "接口名称：dialCall（发起CTD呼叫）<br/>",
			"dialCallDesc" : "此接口用于在主叫和被叫之间发起CTD呼叫。主叫方和被叫方的号码可以是UC号码、手机号码或固定号码。",
			"initiatorLabel" : "呼叫发起人的账号:",
			"callerLabel" : "主叫号码:",
			"calleeLabel" : "被叫号码:",
			"callIdLabel" : "呼叫标识：",
			"initiatorInputTd" : "呼叫发起人的UC账号或应用账号：<br>UC账号：格式为UC:UC帐号，如UC:j00213891 <br>应用账号：格式为APP:appid，如APP:000011112512（暂不支持）",
			"callerInputTd" : "主叫号码<br>说明：支持UC号码、手机号码、电话号码三种形式。其中，手机号码、电话号码必须是E.164格式（国际公共电话号码方案，格式为：国家码+国内目的码+用户号码，如：+86-10-62618501）。",
			"calleeInputTd" : "被叫号码<br>说明：支持UC号码、手机号码、电话号码三种形式。其中，手机号码、电话号码必须是E.164格式（国际公共电话号码方案，格式为：国家码+国内目的码+用户号码，如：+86-10-62618501）。",
			"callIdOutputTd" : "呼叫标志",
			
			"initiatorNull" : "呼叫发起人的UC账号或应用账号不能为空",
			"callerNull" : "主叫号码不能为空",
			"calleeNull" : "被叫号码不能为空",
			
			
			"appSendMsgToUCInterface" : "接口名称：appSendMsgToUC(向UC用户发送消息) <br/>",
			"appSendMsgToUCDesc" : "此接口用于从第三方应用向UC用户发送消息",
			"sendNumberLabel" : "消息接入码:", 
			"ucAccountLabel" : "接收者UC账号:", 
			"messageLabel" : "消息内容:", 
			"messageAttention":"注：此处的消息文需经过Base64编码处理。<br/>例如：消息'&lt;imbody&gt;&lt;content&gt;Hellow World!&lt;/content&gt;&lt;/imbody&gt;'经过Base64处理后为<br/>'PGltYm9keT48Y29udGVudD5IZWxsb3cgV29yb<br/>GQhPC9jb250ZW50PjwvaW1ib2R5Pg=='。",
			"sendNumberInputTd" : "即时消息接入码<br>例如：“99991234”，该值在BME中的OBG应用管理配置项，用户开户时配置。",
			"ucAccountInputTd" : "接收者UC账号",
			"messageInputTd" : "消息内容 (Base64编码)<br>消息内容的格式为：&lt;imbody&gt;&lt;content&gt;内容&lt;/content&gt;&lt;/imbody&gt;",
			
			
			"sendNumberNull" : "即时消息接入码不能为空",
			"ucAccountNull" : "接收者UC账号不能为空",
			"ucMessageNull" : "消息内容不能为空",
			
			
			"createConfInterface" : "接口名称：createConf（发起会议）<br/>",
			"createConfDesc" : "此接口用于发起会议",
			"confInfoInputTd" : "准备创建的会议参数",
			"confTypeInputTd" : "会议类型：<br> 1：即时会议<br>2：预约会议 <br>3：需要预留多媒体资源的即时会议 <br>4：需要预留多媒体资源的预约会议 ",
			"confSubjectInputTd" : "会议主题",
			"initiatorConfInputTd" : "会议发起者的UC账号",
			"beginTimeInputTd" : "预约会议开始时间(如果是即时会议，该属性无效)",
			"endTimeInputTd" : "预约会议结束时间(如果是即时会议，该属性无效)",
			"conferenceParamLabel" : "发起会议",
			"ConfUserInputTd" : "会议主席",
			"ConfUsersInputTd" : "会议成员列表：<br>说明：即时会议（confType=1，3），不支持此字段。会议发起方在收到主持人与会成功的通知后，再调用添加与会者接口addIntoConf增加会议成员。",
			"mediaTypeInputTd" : "会议媒体类型（二进制表示，特定位置为1表示开通该功能，0表示未开通该功能）：<br>第一位：音频<br>第二位：视频<br>第三位：数据<br>说明:会议媒体类型可以进行组合，如111表示会议媒体类型为音视频加数据，100表示会议媒体类型为音频。目前仅支持100和111。",
			"chairmanPasswordInputTd" : "会议主席密码<br>说明：密码长度默认为9位或9位以上，且不能同UC系统中已预约的会议密码相同。（即时会议暂不支持）",
			"memberPasswordInputTd" : "普通成员会议密码<br>说明：密码长度默认为9位或9位以上，且不能同UC系统中已预约的会议密码相同。（即时会议暂不支持）",
			"maxAttendeeInputTd" : "最大与会者人数，最大与会人数可以在数据库中配置，默认为480人以内",
			"confUserNumberInputTd" : "与会者号码，支持UC号码、手机号码、区号+固定电话号码",
			"confUserNameInputTd" : "与会者姓名",
			"confUserAccountInputTd" : "与会者UC账号",
			"confUserTalkModeInputTd" : "发话权：<br>0：无发话权<br>1：有发话权<br>2：正在申请",
			"confUserStatusInputTd" : "与会者状态：<br>1：正在邀请<br>2：邀请成功<br>3：邀请失败<br>4：挂断",
			"isSupportVideoInputTd" : "用户是否支持视频：<br>0：支持<br>1：不支持",
			"confUserRoleInputTd" : "用户角色：<br>1：主持人<br>2：普通成员",
			"confUserEmailInputTd" : "与会者Email，如zhangsan@huawei.com",
			"confIdOutputTd" : "会议标志",
			"confIdLabel" : "会议标志：",
			"confTypeLabel" : "会议类型：",
			"confTypeOption1" : "即时会议",
			"confTypeOption2" : "预约会议",
			"confTypeOption3" : "需要预留多媒体资源的即时会议",
			"confTypeOption4" : "需要预留多媒体资源的预约会议",
			"subjectLabel" : "会议主题：",
			"confInitiatorLabel" : "会议发起者的UC账号：",
			"confBeginTimeLabel" : "开始时间(yyyy/mm/dd hh:mm)：",
			"confEndTimeLabel" : "结束时间(yyyy/mm/dd hh:mm)：",
			"chairmanNumberLabel" : "主席号码：",
			"chairmanNameLabel" : "主席姓名：",
			"chairmanAccountLabel" : "主席UC账号：",
			"chairmanTalkModeLabel" : "发话权：",
			"chairmanStatusLabel" : "主席状态：",
			"chairmanSupportVideoLabel" : "是否支持视频：",
			"chairmanRoleLabel" : "角色：",
			"chairmanEmailLabel" : "Email：",
			"mediaTypeLabel" : "媒体类型：",
			"chairmanPasswordLabel" : "主席密码：",
			"memberPasswordLabel" : "成员密码：",
			"maxAttendeeLabel" : "最大与会者人数：",
			
			
			"TalkMode0" : "无发话权",
			"TalkMode1" : "有发话权",
			"TalkMode2" : "正在申请",
			
			"statusOption1" : "正在邀请",
			"statusOption2" : "邀请成功",
			"statusOption3" : "邀请失败",
			"statusOption4" : "挂断",
			
			"supportVideoOption0" : "支持",
			"supportVideoOption1" : "不支持",
			
			"roleOption1" : "主持人",
			"roleOption2" : "普通成员",
			
			"mediaTypeSpan1" : "音频",
			"mediaTypeSpan2" : "视频",
			"mediaTypeSpan3" : "数据",
			
			"confUserNumberErrTip" : "与会者号码不能为空",
			"subjectErrTip" : "会议主题不能为空",
			"initiatorErrTip" : "会议发起者的账号不能为空",
			"chairmanNumberErrTip" : "主席号码不能为空",
			"maxAttendeeNullErrTip" : "最大与会者人数不能为空",
			"maxAttendeeErrTip" : "最大与会者人数只能为数字",
			"chairmanEmailErrTip" : "主席Email格式不正确",
			"confUserEmailErrTip" : "与会者Email格式不正确",
			"confBeginTimeErrTip" : "时间格式为：yyyy/mm/dd hh:mm,例如：2014/02/13 08:30",
			"confEndTimeErrTip" : "时间格式为：yyyy/mm/dd hh:mm,例如：2014/02/13 08:30",
			
			
			"confUserParamBtn" : "添加与会者",
			"confUserNumberLabel" : "与会者号码",
			"confUserNameLabel" : "与会者姓名",
			"confUserAccountLabel" : "与会者UC账号",
			"confUserTalkModeLabel" : "发话权",
			"confUserStatusLabel" : "与会者状态",
			"confUserSupportVideoLabel" : "是否支持视频",
			"confUserRoleLabel" : "角色",
			"confUserEmailLabel" : "Email",
			"confUserOptionLabel" : "操作"
		}
	};
}