package com.huawei.esdk.platform.professional.local.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.10
 * 2014-07-11T14:27:06.993+08:00
 * Generated source version: 2.6.10
 * 
 */
@WebService(targetNamespace = "esdk_platform", name = "Platform.KeyMgr")
@XmlSeeAlso({ObjectFactory.class})
public interface PlatformKeyMgr {

    @RequestWrapper(localName = "getPublicKey", targetNamespace = "esdk_platform", className = "com.huawei.esdk.platform.northcommu.cxf.professional.gen.GetPublicKey")
    @WebMethod(action = "esdk_platformgetPublicKey")
    @ResponseWrapper(localName = "getPublicKeyResponse", targetNamespace = "esdk_platform", className = "com.huawei.esdk.platform.northcommu.cxf.professional.gen.GetPublicKeyResponse")
    public void getPublicKey(
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "publicKey", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> publicKey
    );
}
