package com.huawei.esdk.uc.professional.local.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-10-15T18:36:15.965+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "esdk_uc_professional_server", name = "UCProfessional.UserProfile.PSSvr")
@XmlSeeAlso({ObjectFactory.class})
public interface UCProfessionalUserProfilePSSvr {

    @RequestWrapper(localName = "queryUCPresence", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.QueryUCPresence")
    @WebMethod(action = "esdk_uc_professional_server.queryUCPresence")
    @ResponseWrapper(localName = "queryUCPresenceResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.QueryUCPresenceResponse")
    public void queryUCPresence(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.util.List<java.lang.String> ucAccount,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "presInfoResult", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.huawei.esdk.uc.professional.local.bean.PresInfoResult>> presInfoResult
    );
}
