package com.huawei.esdk.uc.professional.local.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.huawei.esdk.uc.professional.local.bean.CallStatusInfo;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-10-15T18:36:15.808+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "esdk_uc_professional_server", name = "UCProfessional.CTD")
@XmlSeeAlso({ObjectFactory.class})
public interface UCProfessionalCTD {

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "releaseCall", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.ReleaseCall")
    @WebMethod(action = "esdk_uc_professional_server.releaseCall")
    @ResponseWrapper(localName = "releaseCallResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.ReleaseCallResponse")
    public java.lang.Integer releaseCall(
        @WebParam(name = "callId", targetNamespace = "")
        java.lang.String callId
    );

    @RequestWrapper(localName = "dialCall", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DialCall")
    @WebMethod(action = "esdk_uc_professional_server.dialCall")
    @ResponseWrapper(localName = "dialCallResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DialCallResponse")
    public void dialCall(
        @WebParam(name = "initiator", targetNamespace = "")
        java.lang.String initiator,
        @WebParam(name = "caller", targetNamespace = "")
        java.lang.String caller,
        @WebParam(name = "callee", targetNamespace = "")
        java.lang.String callee,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "callId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> callId
    );

    @RequestWrapper(localName = "getCallStatus", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.GetCallStatus")
    @WebMethod(action = "esdk_uc_professional_server.getCallStatus")
    @ResponseWrapper(localName = "getCallStatusResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.GetCallStatusResponse")
    public void getCallStatus(
        @WebParam(name = "callId", targetNamespace = "")
        java.lang.String callId,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "callStatusInfo", targetNamespace = "")
        javax.xml.ws.Holder<CallStatusInfo> callStatusInfo
    );
}
