package com.huawei.esdk.uc.professional.local.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-10-15T18:36:15.902+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "esdk_uc_professional_server", name = "UCProfessional.VoiceService.ForwardNumber")
@XmlSeeAlso({ObjectFactory.class})
public interface UCProfessionalVoiceServiceForwardNumber {

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "setForwardService", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.SetForwardService")
    @WebMethod(action = "esdk_uc_professional_server.setForwardService")
    @ResponseWrapper(localName = "setForwardServiceResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.SetForwardServiceResponse")
    public java.lang.Integer setForwardService(
        @WebParam(name = "userNumber", targetNamespace = "")
        java.lang.String userNumber,
        @WebParam(name = "forwardType", targetNamespace = "")
        java.lang.String forwardType,
        @WebParam(name = "forwardNumber", targetNamespace = "")
        java.lang.String forwardNumber
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "unsetForwardService", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.UnsetForwardService")
    @WebMethod(action = "esdk_uc_professional_server.unsetForwardService")
    @ResponseWrapper(localName = "unsetForwardServiceResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.UnsetForwardServiceResponse")
    public java.lang.Integer unsetForwardService(
        @WebParam(name = "userNumber", targetNamespace = "")
        java.lang.String userNumber,
        @WebParam(name = "forwardType", targetNamespace = "")
        java.lang.String forwardType
    );

    @RequestWrapper(localName = "queryForwardService", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.QueryForwardService")
    @WebMethod(action = "esdk_uc_professional_server.queryForwardService")
    @ResponseWrapper(localName = "queryForwardServiceResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.QueryForwardServiceResponse")
    public void queryForwardService(
        @WebParam(name = "userNumber", targetNamespace = "")
        java.lang.String userNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "forwardNumberInfo", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.huawei.esdk.uc.professional.local.bean.ForwardNumberInfo>> forwardNumberInfo
    );
}
