package com.huawei.esdk.uc.professional.local.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.huawei.esdk.uc.professional.local.bean.PageInfo;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-10-15T18:36:15.918+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "esdk_uc_professional_server", name = "UCProfessional.UserProfile.PublicGroup")
@XmlSeeAlso({ObjectFactory.class})
public interface UCProfessionalUserProfilePublicGroup {

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "delGroupMember", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DelGroupMember")
    @WebMethod(action = "esdk_uc_professional_server.delGroupMember")
    @ResponseWrapper(localName = "delGroupMemberResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DelGroupMemberResponse")
    public java.lang.Integer delGroupMember(
        @WebParam(name = "groupId", targetNamespace = "")
        java.lang.String groupId,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "groupName", targetNamespace = "")
        java.lang.String groupName
    );

    @RequestWrapper(localName = "queryGroupInfo", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.QueryGroupInfo")
    @WebMethod(action = "esdk_uc_professional_server.queryGroupInfo")
    @ResponseWrapper(localName = "queryGroupInfoResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.QueryGroupInfoResponse")
    public void queryGroupInfo(
        @WebParam(name = "groupId", targetNamespace = "")
        java.lang.String groupId,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "groupInfo", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.huawei.esdk.uc.professional.local.bean.GroupInfo>> groupInfo
    );

    @RequestWrapper(localName = "queryGroupList", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.QueryGroupList")
    @WebMethod(action = "esdk_uc_professional_server.queryGroupList")
    @ResponseWrapper(localName = "queryGroupListResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.QueryGroupListResponse")
    public void queryGroupList(
        @WebParam(name = "queryMode", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.QueryMode queryMode,
        @WebParam(name = "groupNumber", targetNamespace = "")
        java.lang.String groupNumber,
        @WebParam(name = "groupName", targetNamespace = "")
        java.lang.String groupName,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "pageInfo", targetNamespace = "")
        javax.xml.ws.Holder<PageInfo> pageInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "groupInfoBase", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.huawei.esdk.uc.professional.local.bean.GroupInfoBase>> groupInfoBase
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "modifyGroup", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.ModifyGroup")
    @WebMethod(action = "esdk_uc_professional_server.modifyGroup")
    @ResponseWrapper(localName = "modifyGroupResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.ModifyGroupResponse")
    public java.lang.Integer modifyGroup(
        @WebParam(name = "groupId", targetNamespace = "")
        java.lang.String groupId,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(name = "groupModifyInfo", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.GroupModifyInfo groupModifyInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "modifyGroupOwner", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.ModifyGroupOwner")
    @WebMethod(action = "esdk_uc_professional_server.modifyGroupOwner")
    @ResponseWrapper(localName = "modifyGroupOwnerResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.ModifyGroupOwnerResponse")
    public java.lang.Integer modifyGroupOwner(
        @WebParam(name = "groupId", targetNamespace = "")
        java.lang.String groupId,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(name = "groupName", targetNamespace = "")
        java.lang.String groupName,
        @WebParam(name = "memberUri", targetNamespace = "")
        java.lang.String memberUri,
        @WebParam(name = "ownerFlag", targetNamespace = "")
        java.lang.String ownerFlag
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "delGroup", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DelGroup")
    @WebMethod(action = "esdk_uc_professional_server.delGroup")
    @ResponseWrapper(localName = "delGroupResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DelGroupResponse")
    public java.lang.Integer delGroup(
        @WebParam(name = "groupId", targetNamespace = "")
        java.lang.String groupId,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator
    );

    @RequestWrapper(localName = "addGroupMemberBatch", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddGroupMemberBatch")
    @WebMethod(action = "esdk_uc_professional_server.addGroupMemberBatch")
    @ResponseWrapper(localName = "addGroupMemberBatchResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddGroupMemberBatchResponse")
    public void addGroupMemberBatch(
        @WebParam(name = "groupId", targetNamespace = "")
        java.lang.String groupId,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(name = "groupName", targetNamespace = "")
        java.lang.String groupName,
        @WebParam(name = "groupMember", targetNamespace = "")
        java.util.List<com.huawei.esdk.uc.professional.local.bean.GroupMember> groupMember,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "groupRetInfo", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.huawei.esdk.uc.professional.local.bean.BatchResultInfo>> groupRetInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "addGroupMember", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddGroupMember")
    @WebMethod(action = "esdk_uc_professional_server.addGroupMember")
    @ResponseWrapper(localName = "addGroupMemberResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddGroupMemberResponse")
    public java.lang.Integer addGroupMember(
        @WebParam(name = "groupId", targetNamespace = "")
        java.lang.String groupId,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "groupName", targetNamespace = "")
        java.lang.String groupName
    );

    @RequestWrapper(localName = "queryGroupMember", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.QueryGroupMember")
    @WebMethod(action = "esdk_uc_professional_server.queryGroupMember")
    @ResponseWrapper(localName = "queryGroupMemberResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.QueryGroupMemberResponse")
    public void queryGroupMember(
        @WebParam(name = "queryMode", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.QueryMode queryMode,
        @WebParam(name = "groupId", targetNamespace = "")
        java.lang.String groupId,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "pageInfo", targetNamespace = "")
        javax.xml.ws.Holder<PageInfo> pageInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "groupMember", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.huawei.esdk.uc.professional.local.bean.GroupMember>> groupMember
    );

    @RequestWrapper(localName = "delGroupMemberBatch", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DelGroupMemberBatch")
    @WebMethod(action = "esdk_uc_professional_server.delGroupMemberBatch")
    @ResponseWrapper(localName = "delGroupMemberBatchResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DelGroupMemberBatchResponse")
    public void delGroupMemberBatch(
        @WebParam(name = "groupId", targetNamespace = "")
        java.lang.String groupId,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(name = "groupName", targetNamespace = "")
        java.lang.String groupName,
        @WebParam(name = "groupMember", targetNamespace = "")
        java.util.List<com.huawei.esdk.uc.professional.local.bean.GroupMember> groupMember,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "groupRetInfo", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.huawei.esdk.uc.professional.local.bean.BatchResultInfo>> groupRetInfo
    );

    @RequestWrapper(localName = "addGroup", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddGroup")
    @WebMethod(action = "esdk_uc_professional_server.addGroup")
    @ResponseWrapper(localName = "addGroupResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddGroupResponse")
    public void addGroup(
        @WebParam(name = "groupInfo", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.GroupInfo groupInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "groupNumber", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> groupNumber
    );

    @RequestWrapper(localName = "queryJoinGroupByUser", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.QueryJoinGroupByUser")
    @WebMethod(action = "esdk_uc_professional_server.queryJoinGroupByUser")
    @ResponseWrapper(localName = "queryJoinGroupByUserResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.QueryJoinGroupByUserResponse")
    public void queryJoinGroupByUser(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "queryMode", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.QueryMode queryMode,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "pageInfo", targetNamespace = "")
        javax.xml.ws.Holder<PageInfo> pageInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "joinGroupInfo", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.huawei.esdk.uc.professional.local.bean.JoinGroupInfo>> joinGroupInfo
    );
}
