package com.huawei.esdk.uc.professional.local.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.huawei.esdk.uc.professional.local.bean.ConferenceInfo;
import com.huawei.esdk.uc.professional.local.bean.PageInfo;
import com.huawei.esdk.uc.professional.local.bean.TerminalInConfInfo;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-10-15T18:36:15.557+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "esdk_uc_professional_server", name = "UCProfessional.CTC")
@XmlSeeAlso({ObjectFactory.class})
public interface UCProfessionalCTC {

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "joinConf", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.JoinConf")
    @WebMethod(action = "esdk_uc_professional_server.joinConf")
    @ResponseWrapper(localName = "joinConfResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.JoinConfResponse")
    public java.lang.Integer joinConf(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "confId", targetNamespace = "")
        java.lang.String confId,
        @WebParam(name = "number", targetNamespace = "")
        java.lang.String number,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "role", targetNamespace = "")
        java.lang.String role
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "subConfStatus", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.SubConfStatus")
    @WebMethod(action = "esdk_uc_professional_server.subConfStatus")
    @ResponseWrapper(localName = "subConfStatusResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.SubConfStatusResponse")
    public java.lang.Integer subConfStatus(
        @WebParam(name = "appId", targetNamespace = "")
        java.lang.String appId,
        @WebParam(name = "confId", targetNamespace = "")
        java.lang.String confId
    );

    @RequestWrapper(localName = "getConfList", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.GetConfList")
    @WebMethod(action = "esdk_uc_professional_server.getConfList")
    @ResponseWrapper(localName = "getConfListResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.GetConfListResponse")
    public void getConfList(
        @WebParam(name = "initiator", targetNamespace = "")
        java.lang.String initiator,
        @WebParam(name = "queryType", targetNamespace = "")
        java.lang.String queryType,
        @WebParam(name = "beginTime", targetNamespace = "")
        java.util.Date beginTime,
        @WebParam(name = "endTime", targetNamespace = "")
        java.util.Date endTime,
        @WebParam(mode = WebParam.Mode.INOUT, name = "pageInfo", targetNamespace = "")
        javax.xml.ws.Holder<PageInfo> pageInfo,
        @WebParam(name = "confType", targetNamespace = "")
        java.lang.String confType,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "confSummary", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.huawei.esdk.uc.professional.local.bean.ConfSummary>> confSummary
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "audioToVideoConf", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AudioToVideoConf")
    @WebMethod(action = "esdk_uc_professional_server.audioToVideoConf")
    @ResponseWrapper(localName = "audioToVideoConfResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AudioToVideoConfResponse")
    public java.lang.Integer audioToVideoConf(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "confId", targetNamespace = "")
        java.lang.String confId
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "delFromConf", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DelFromConf")
    @WebMethod(action = "esdk_uc_professional_server.delFromConf")
    @ResponseWrapper(localName = "delFromConfResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DelFromConfResponse")
    public java.lang.Integer delFromConf(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "confId", targetNamespace = "")
        java.lang.String confId,
        @WebParam(name = "confUser", targetNamespace = "")
        java.util.List<com.huawei.esdk.uc.professional.local.bean.ConfUser> confUser
    );

    @RequestWrapper(localName = "getConfInfo", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.GetConfInfo")
    @WebMethod(action = "esdk_uc_professional_server.getConfInfo")
    @ResponseWrapper(localName = "getConfInfoResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.GetConfInfoResponse")
    public void getConfInfo(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "confId", targetNamespace = "")
        java.lang.String confId,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "conferenceInfo", targetNamespace = "")
        javax.xml.ws.Holder<ConferenceInfo> conferenceInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "endConf", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.EndConf")
    @WebMethod(action = "esdk_uc_professional_server.endConf")
    @ResponseWrapper(localName = "endConfResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.EndConfResponse")
    public java.lang.Integer endConf(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "confId", targetNamespace = "")
        java.lang.String confId
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "addIntoConf", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddIntoConf")
    @WebMethod(action = "esdk_uc_professional_server.addIntoConf")
    @ResponseWrapper(localName = "addIntoConfResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddIntoConfResponse")
    public java.lang.Integer addIntoConf(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "confId", targetNamespace = "")
        java.lang.String confId,
        @WebParam(name = "confUser", targetNamespace = "")
        java.util.List<com.huawei.esdk.uc.professional.local.bean.ConfUser> confUser
    );

    @RequestWrapper(localName = "informTerminalType", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.InformTerminalType")
    @WebMethod(action = "esdk_uc_professional_server.informTerminalType")
    @ResponseWrapper(localName = "informTerminalTypeResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.InformTerminalTypeResponse")
    public void informTerminalType(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "confId", targetNamespace = "")
        java.lang.String confId,
        @WebParam(name = "terminalType", targetNamespace = "")
        java.lang.String terminalType,
        @WebParam(name = "terminalIP", targetNamespace = "")
        java.lang.String terminalIP,
        @WebParam(name = "location", targetNamespace = "")
        java.lang.String location,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "terminalInConfInfo", targetNamespace = "")
        javax.xml.ws.Holder<TerminalInConfInfo> terminalInConfInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "viewSite", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.ViewSite")
    @WebMethod(action = "esdk_uc_professional_server.viewSite")
    @ResponseWrapper(localName = "viewSiteResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.ViewSiteResponse")
    public java.lang.Integer viewSite(
        @WebParam(name = "confId", targetNamespace = "")
        java.lang.String confId,
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "videoSourceUri", targetNamespace = "")
        java.lang.String videoSourceUri,
        @WebParam(name = "isLock", targetNamespace = "")
        java.lang.Integer isLock
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "modifyTalkMode", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.ModifyTalkMode")
    @WebMethod(action = "esdk_uc_professional_server.modifyTalkMode")
    @ResponseWrapper(localName = "modifyTalkModeResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.ModifyTalkModeResponse")
    public java.lang.Integer modifyTalkMode(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "confId", targetNamespace = "")
        java.lang.String confId,
        @WebParam(name = "number", targetNamespace = "")
        java.lang.String number,
        @WebParam(name = "talkMode", targetNamespace = "")
        java.lang.Integer talkMode
    );

    @RequestWrapper(localName = "createConf", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.CreateConf")
    @WebMethod(action = "esdk_uc_professional_server.createConf")
    @ResponseWrapper(localName = "createConfResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.CreateConfResponse")
    public void createConf(
        @WebParam(name = "confInfo", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.ConferenceInfo confInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "confId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> confId
    );
}
