package com.huawei.esdk.uc.professional.local.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.huawei.esdk.uc.professional.local.bean.FriendInfo;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-10-15T18:36:15.933+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "esdk_uc_professional_server", name = "UCProfessional.UserProfile.Friend")
@XmlSeeAlso({ObjectFactory.class})
public interface UCProfessionalUserProfileFriend {

    @RequestWrapper(localName = "getFriendInfo", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.GetFriendInfo")
    @WebMethod(action = "esdk_uc_professional_server.getFriendInfo")
    @ResponseWrapper(localName = "getFriendInfoResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.GetFriendInfoResponse")
    public void getFriendInfo(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "type", targetNamespace = "")
        java.lang.Integer type,
        @WebParam(name = "friendAccount", targetNamespace = "")
        java.lang.String friendAccount,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "friendInfo", targetNamespace = "")
        javax.xml.ws.Holder<FriendInfo> friendInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "addFriend", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddFriend")
    @WebMethod(action = "esdk_uc_professional_server.addFriend")
    @ResponseWrapper(localName = "addFriendResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddFriendResponse")
    public java.lang.Integer addFriend(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "friendAccount", targetNamespace = "")
        java.lang.String friendAccount
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "delFriend", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DelFriend")
    @WebMethod(action = "esdk_uc_professional_server.delFriend")
    @ResponseWrapper(localName = "delFriendResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DelFriendResponse")
    public java.lang.Integer delFriend(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "friendAccount", targetNamespace = "")
        java.lang.String friendAccount
    );

    @RequestWrapper(localName = "getFriendList", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.GetFriendList")
    @WebMethod(action = "esdk_uc_professional_server.getFriendList")
    @ResponseWrapper(localName = "getFriendListResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.GetFriendListResponse")
    public void getFriendList(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "friendInfo", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.huawei.esdk.uc.professional.local.bean.FriendInfo>> friendInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "addNewFriend", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddNewFriend")
    @WebMethod(action = "esdk_uc_professional_server.addNewFriend")
    @ResponseWrapper(localName = "addNewFriendResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddNewFriendResponse")
    public java.lang.Integer addNewFriend(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "friendAccount", targetNamespace = "")
        java.lang.String friendAccount,
        @WebParam(name = "customLinkmanInfo", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.CustomLinkmanInfo customLinkmanInfo,
        @WebParam(name = "teamId", targetNamespace = "")
        java.lang.String teamId
    );

    @RequestWrapper(localName = "getPersonIncFriendList", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.GetPersonIncFriendList")
    @WebMethod(action = "esdk_uc_professional_server.getPersonIncFriendList")
    @ResponseWrapper(localName = "getPersonIncFriendListResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.GetPersonIncFriendListResponse")
    public void getPersonIncFriendList(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "timeStamp", targetNamespace = "")
        java.util.Date timeStamp,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "friendChangeInfo", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.huawei.esdk.uc.professional.local.bean.FriendChangeInfo>> friendChangeInfo
    );
}
