package com.huawei.esdk.uc.professional.local.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-10-15T18:36:15.918+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "esdk_uc_professional_server", name = "UCProfessional.VoiceService.BlackWhiteNumber")
@XmlSeeAlso({ObjectFactory.class})
public interface UCProfessionalVoiceServiceBlackWhiteNumber {

    @RequestWrapper(localName = "setBlackWhiteListState", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.SetBlackWhiteListState")
    @WebMethod(action = "esdk_uc_professional_server.setBlackWhiteListState")
    @ResponseWrapper(localName = "setBlackWhiteListStateResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.SetBlackWhiteListStateResponse")
    public void setBlackWhiteListState(
        @WebParam(name = "userNumber", targetNamespace = "")
        java.lang.String userNumber,
        @WebParam(name = "blackWhiteListFlag", targetNamespace = "")
        java.lang.String blackWhiteListFlag,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultMessage", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> resultMessage
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "setBlackWhiteService", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.SetBlackWhiteService")
    @WebMethod(action = "esdk_uc_professional_server.setBlackWhiteService")
    @ResponseWrapper(localName = "setBlackWhiteServiceResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.SetBlackWhiteServiceResponse")
    public java.lang.Integer setBlackWhiteService(
        @WebParam(name = "userNumber", targetNamespace = "")
        java.lang.String userNumber,
        @WebParam(name = "operationType", targetNamespace = "")
        java.lang.String operationType,
        @WebParam(name = "flowType", targetNamespace = "")
        java.lang.String flowType,
        @WebParam(name = "blackWhiteListFlag", targetNamespace = "")
        java.lang.String blackWhiteListFlag,
        @WebParam(name = "blackWhiteNumberScope", targetNamespace = "")
        java.util.List<com.huawei.esdk.uc.professional.local.bean.BlackWhiteNumberScope> blackWhiteNumberScope
    );

    @RequestWrapper(localName = "queryBlackWhiteService", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.QueryBlackWhiteService")
    @WebMethod(action = "esdk_uc_professional_server.queryBlackWhiteService")
    @ResponseWrapper(localName = "queryBlackWhiteServiceResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.QueryBlackWhiteServiceResponse")
    public void queryBlackWhiteService(
        @WebParam(name = "userNumber", targetNamespace = "")
        java.lang.String userNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "blackWhiteList", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.huawei.esdk.uc.professional.local.bean.BlackWhiteList>> blackWhiteList
    );
}
