package com.huawei.esdk.uc.professional.local.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-10-15T18:36:15.871+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "esdk_uc_professional_server", name = "UCProfessional.BMP.AccountMaintenance")
@XmlSeeAlso({ObjectFactory.class})
public interface UCProfessionalBMPAccountMaintenance {

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "updateAccount", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.UpdateAccount")
    @WebMethod(action = "esdk_uc_professional_server.updateAccount")
    @ResponseWrapper(localName = "updateAccountResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.UpdateAccountResponse")
    public java.lang.Integer updateAccount(
        @WebParam(name = "accountInfo", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.AccountInfo accountInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "addDept", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddDept")
    @WebMethod(action = "esdk_uc_professional_server.addDept")
    @ResponseWrapper(localName = "addDeptResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddDeptResponse")
    public java.lang.Integer addDept(
        @WebParam(name = "deptInfo", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.DeptKeyInfo deptInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "delAccount", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DelAccount")
    @WebMethod(action = "esdk_uc_professional_server.delAccount")
    @ResponseWrapper(localName = "delAccountResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DelAccountResponse")
    public java.lang.Integer delAccount(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "addAccount", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddAccount")
    @WebMethod(action = "esdk_uc_professional_server.addAccount")
    @ResponseWrapper(localName = "addAccountResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddAccountResponse")
    public java.lang.Integer addAccount(
        @WebParam(name = "accountInfo", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.AccountInfo accountInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "delDept", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DelDept")
    @WebMethod(action = "esdk_uc_professional_server.delDept")
    @ResponseWrapper(localName = "delDeptResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DelDeptResponse")
    public java.lang.Integer delDept(
        @WebParam(name = "deptId", targetNamespace = "")
        java.lang.String deptId
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "updateDept", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.UpdateDept")
    @WebMethod(action = "esdk_uc_professional_server.updateDept")
    @ResponseWrapper(localName = "updateDeptResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.UpdateDeptResponse")
    public java.lang.Integer updateDept(
        @WebParam(name = "deptInfo", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.DeptKeyInfo deptInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "modifyAccount", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.ModifyAccount")
    @WebMethod(action = "esdk_uc_professional_server.modifyAccount")
    @ResponseWrapper(localName = "modifyAccountResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.ModifyAccountResponse")
    public java.lang.Integer modifyAccount(
        @WebParam(name = "accountInfo", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.AccountInfo accountInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "modifyDept", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.ModifyDept")
    @WebMethod(action = "esdk_uc_professional_server.modifyDept")
    @ResponseWrapper(localName = "modifyDeptResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.ModifyDeptResponse")
    public java.lang.Integer modifyDept(
        @WebParam(name = "deptInfo", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.DeptKeyInfo deptInfo
    );
}
