package com.huawei.esdk.uc.professional.local.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.huawei.esdk.uc.professional.local.bean.NumberInfo;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-10-15T18:36:15.886+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "esdk_uc_professional_server", name = "UCProfessional.BMP.Number")
@XmlSeeAlso({ObjectFactory.class})
public interface UCProfessionalBMPNumber {

    @RequestWrapper(localName = "queryNumber", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.QueryNumber")
    @WebMethod(action = "esdk_uc_professional_server.queryNumber")
    @ResponseWrapper(localName = "queryNumberResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.QueryNumberResponse")
    public void queryNumber(
        @WebParam(mode = WebParam.Mode.INOUT, name = "numberInfo", targetNamespace = "")
        javax.xml.ws.Holder<NumberInfo> numberInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "modifyNumber", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.ModifyNumber")
    @WebMethod(action = "esdk_uc_professional_server.modifyNumber")
    @ResponseWrapper(localName = "modifyNumberResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.ModifyNumberResponse")
    public java.lang.Integer modifyNumber(
        @WebParam(name = "numberInfo", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.NumberInfo numberInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "delNumber", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DelNumber")
    @WebMethod(action = "esdk_uc_professional_server.delNumber")
    @ResponseWrapper(localName = "delNumberResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.DelNumberResponse")
    public java.lang.Integer delNumber(
        @WebParam(name = "corpInterNumber", targetNamespace = "")
        java.lang.String corpInterNumber
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "addNumber", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddNumber")
    @WebMethod(action = "esdk_uc_professional_server.addNumber")
    @ResponseWrapper(localName = "addNumberResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.AddNumberResponse")
    public java.lang.Integer addNumber(
        @WebParam(name = "numberInfo", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.NumberInfo numberInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "numberBind", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.NumberBind")
    @WebMethod(action = "esdk_uc_professional_server.numberBind")
    @ResponseWrapper(localName = "numberBindResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.NumberBindResponse")
    public java.lang.Integer numberBind(
        @WebParam(name = "bindInfo", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.BindInfo bindInfo
    );
}
