function LanguageControllerEN() {
	this.language = {
		buttons : {
			"dialCallBtn" : "dialCall",
			"appSendMsgToUCBtn" : "appSendMsgToUC",
			"createConfBtn" : "Schedule Conference"
		},

		titles : {
			"descriptionUC" : "This Demo contains examples of using UC three interfaces: dialCall (CTD initiated a call), appSendMsgToUC (send a message to UC users), createConf (sponsored conference)",
			"copyright" : "Copyright © Huawei Technologies Co., Ltd. 1998-2015. All rights reserved.",
			"description" : "Description",
			"exection" : "Execution",
			"sourceCode" : "Source Code",
			"inputParam" : "input:",
			"outputParam" : "output:",
			"resultCode" : "resultCode:",
			"inputParameterDesc" : "input parameters description:",
			"outputParameterDesc" : "output parameters description:",
			"inputParameterTd" : "parameter",
			"inputTypeTd" : "type",
			"inputRestrictionTd" : "restriction",
			"inputDescriptionTd" : "description",
			"outputParameterTd" : "parameter",
			"outputTypeTd" : "type",
			"outputRestrictionTd" : "restriction",
			"outputDescriptionTd" : "description",
			"resultCodeTd" : "for successful return zero, and failed return other codes",
			"operationSuccess" : "operation success",
			"operationFailed" : "operation failed",
			"reserveTd32" : "Reserved field<br>The maximum length is 32 bytes",
			"reserveTd64" : "Reserved field<br>The maximum length is 64 bytes",

			"ucTree_1_span" : "Typical functions",
			"ucTree_2_span" : "CTD",
			"ucTree_3_span" : "dialCall",
			"ucTree_4_span" : "IM",
			"ucTree_5_span" : "appSendMsgToUC",
			"ucTree_6_span" : "Conference",
			"ucTree_7_span" : "createConf",

			"ucTree_1_span_tag" : "",
			"ucTree_2_span_tag" : "",
			"ucTree_3_span_tag" : "",

			"interfaceName" : "interfaceName",
			"interfaceFunction" : "interfaceFunction",

			"dialCallInterface" : "Function Name：dialCall<br/>",
			"dialCallDesc" : "CTD call",
			"initiatorLabel" : "initiator:",
			"callerLabel" : "caller:",
			"calleeLabel" : "callee:",
			"callIdLabel" : "call Id:",
			"initiatorInputTd" : "initiator: <br> UC Account: Format for UC: UC accounts, such as UC: j00213891 <br> Application Account: Format for APP: appid, such as APP: 000011112512 (not supported)",
			"callerInputTd" : "Caller ID <br> Description: Support UC number, cell phone number, phone number three forms. Among them, the phone number, the phone number must be E.164 format (International Public telephone numbering plan format: country code + country code + subscriber number purposes, such as: + 86-10-62618501).",
			"calleeInputTd" : "Called number <br> Description: Support UC number, cell phone number, phone number three forms. Among them, the phone number, the phone number must be E.164 format (International Public telephone numbering plan format: country code + country code + subscriber number purposes, such as: + 86-10-62618501).",
			"callIdOutputTd" : "call Id",

			"initiatorNull" : "initiator can not be null",
			"alarmEventIdNotNumber" : "caller can not be null",
			"calleeNull" : "callee can not be null",

			"appSendMsgToUCInterface" : "Function Name：appSendMsgToUC <br/>",
			"appSendMsgToUCDesc" : "Send message",
			"sendNumberLabel" : "Send Number:",
			"ucAccountLabel" : "UC Account:",
			"messageLabel" : "Message:",
			"messageAttention" : "Note: Here's the message text and subject to Base64 encoding process. <br/> example: Message '&lt; imbody &gt; &lt; content &gt; Hellow World &lt; / content &gt; &lt; / imbody &gt;!' After Base64 treated as <br/> 'PGltYm9keT48Y29udGVudD5IZWxsb3cgV29yb <br/> GQhPC9jb250ZW50PjwvaW1ib2R5Pg =='.",
			"sendNumberInputTd" : "Instant messaging access code <br> example: \"99991234\", which OBG application management configuration items in the BME, the user account configuration.",
			"ucAccountInputTd" : "uc account",
			"messageInputTd" : "message (Base64 encoded) <br> message content format is: &lt; imbody &gt; &lt; content &gt; content &lt; / content &gt; &lt; / imbody &gt;",

			"sendNumberNull" : "send number can not be null",
			"ucAccountNull" : "uc account can not be null",
			"ucMessageNull" : "message can not be null",

			"createConfInterface" : "Function Name：createConf(Schedule Conference)<br/>",
			"createConfDesc" : "Schedule conference",
			"confInfoInputTd" : "Conference Parameter",
			"confTypeInputTd" : "Conference Type: <br> 1: Instant Meeting <br> 2: Reservation <br> 3: Multimedia resources need to set aside an instant meeting <br> 4: Multimedia resources need to be reserved for Reservation",
			"confSubjectInputTd" : "Conference Topic",
			"initiatorConfInputTd" : "Initiator UC Account",
			"beginTimeInputTd" : "Begin Time (if it is an instant meeting, the property is invalid)",
			"endTimeInputTd" : "End Time (if it is an instant meeting, the property is invalid)",
			"conferenceParamLabel" : "Schedule Conference",
			"ConfUserInputTd" : "Chairman",
			"ConfUsersInputTd" : "Attendee: <br> Description: Instant Meeting (confType = 1,3), does not support this field. Conference initiator host the meeting after receiving notice of success, and then add a call participant interface addIntoConf increase Council.",
			"mediaTypeInputTd" : "Media Type: Conference media type (binary representation for a particular position, said the opening of this function, 0 means that the function is not open): <br> first one: Audio <br> second place: Video <br> third place: Data <br> Description: Conference media types can be combined, such as 111, said the meeting was audio and video media types plus data, 100 indicates the type of audio conferencing media. Currently only supports 100 and 111.",
			"chairmanPasswordInputTd" : "Chairman Password <br> Description: The default password length is nine or nine more, and not with the UC system has reserved conference password. (Instant Meeting does not support).",
			"memberPasswordInputTd" : "Member Password <br> Description: The default password length is 9 or 9 above, and the same can not be with the UC system has reserved conference password. (Instant Meeting does not support).",
			"maxAttendeeInputTd" : "Max Attendee Number, you can configure the maximum number of participants in the database, the default is 480 or less",
			"confUserNumberInputTd" : "Attendee User Number, support UC number, phone number, area code + phone number fixed",
			"confUserNameInputTd" : "Attendee User Name",
			"confUserAccountInputTd" : "Attendee User UC Account",
			"confUserTalkModeInputTd" : "Talk Mode: <br> 0: No speaker right <br> 1: There has spoken right <br> 2: Pending",
			"confUserStatusInputTd" : "Attendee Status: <br> 1: being invited <br> 2: invite successful <br> 3: Invitation failed <br> 4: hang up",
			"isSupportVideoInputTd" : "Support Video: <br> 0: Support <br> 1: not supported",
			"confUserRoleInputTd" : "Attendee Role: <br> 1: Moderator <br> 2: ordinary members",
			"confUserEmailInputTd" : "Email,eg.zhangsan@huawei.com",
			"confIdOutputTd" : "Conference Id",
			"confIdLabel" : "conference Id:",
			"confTypeLabel" : "Conference Type：",
			"confTypeOption1" : "Instant Meeting",
			"confTypeOption2" : "Reservation Meeting",
			"confTypeOption3" : "Multimedia resources need to set aside an instant meeting",
			"confTypeOption4" : "Multimedia resources need to set aside an reservation meeting",
			"subjectLabel" : "Conference Topic:",
			"confInitiatorLabel" : "Initiator UC Account:",
			"confBeginTimeLabel" : "Begin Time(yyyy/mm/dd hh:mm)：",
			"confEndTimeLabel" : "End Time(yyyy/mm/dd hh:mm)：",
			"chairmanNumberLabel" : "Chairman Number:",
			"chairmanNameLabel" : "Chairman Name:",
			"chairmanAccountLabel" : "Chairman Account:",
			"chairmanTalkModeLabel" : "Chairman Talk Mode:",
			"chairmanStatusLabel" : "Chairman Status:",
			"chairmanSupportVideoLabel" : "Support Video:",
			"chairmanRoleLabel" : "Chairman Role:",
			"chairmanEmailLabel" : "Email：",
			"mediaTypeLabel" : "Media Type:",
			"chairmanPasswordLabel" : "Chairman Password:",
			"memberPasswordLabel" : "Member Password:",
			"maxAttendeeLabel" : "Max Attendee:",

			"TalkMode0" : "No speaker right",
			"TalkMode1" : "Have the right speaker",
			"TalkMode2" : "Pending",

			"statusOption1" : "Inviting",
			"statusOption2" : "Invite Success",
			"statusOption3" : "Invitation failed",
			"statusOption4" : "Hang up",

			"supportVideoOption0" : "support",
			"supportVideoOption1" : "not support",

			"roleOption1" : "Host",
			"roleOption2" : "Ordinary members",

			"mediaTypeSpan1" : "Audio",
			"mediaTypeSpan2" : "Video",
			"mediaTypeSpan3" : "Data",

			"confUserNumberErrTip" : "Number of participants can not be empty",
			"subjectErrTip" : "Meeting theme can not be empty",
			"initiatorErrTip" : "Conference originator's account can not be empty",
			"chairmanNumberErrTip" : "Chairman of the numbers can not be empty",
			"maxAttendeeNullErrTip" : "The maximum number of participants can not be empty",
			"chairmanEmailErrTip" : "President Email format is incorrect",
			"confUserEmailErrTip" : "Participants Email format is incorrect",
			"maxAttendeeErrTip" : "The maximum number of participants only number",
			"confBeginTimeErrTip" : "Time format: yyyy / mm / dd hh: mm, for example: 2014/02/13 08:30",
			"confEndTimeErrTip" : "Time format: yyyy / mm / dd hh: mm, for example: 2014/02/13 08:30",

			"confUserParamBtn" : "Add Attendee",
			"confUserNumberLabel" : "Attendee Num",
			"confUserNameLabel" : "Attendee Name",
			"confUserAccountLabel" : "Account",
			"confUserTalkModeLabel" : "Talk Mode",
			"confUserStatusLabel" : "Status",
			"confUserSupportVideoLabel" : "Support Video",
			"confUserRoleLabel" : "Role",
			"confUserEmailLabel" : "Email",
			"confUserOptionLabel" : "Option"
		}
	};
}