package com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-09-09T19:36:59.560+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "esdk_uc_professional_server", name = "UCProfessional.Client.Common")
@XmlSeeAlso({ObjectFactory.class})
public interface UCProfessionalClientCommon {

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "userLogout", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.UserLogout")
    @WebMethod(action = "esdk_uc_professional_server.userLogout")
    @ResponseWrapper(localName = "userLogoutResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.UserLogoutResponse")
    public java.lang.Integer userLogout(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "userLogin", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.UserLogin")
    @WebMethod(action = "esdk_uc_professional_server.userLogin")
    @ResponseWrapper(localName = "userLoginResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.UserLoginResponse")
    public java.lang.Integer userLogin(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "registerFunc", targetNamespace = "")
        java.lang.String registerFunc
    );
}
