package com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.huawei.esdk.uc.professional.local.bean.clientmanager.ResPubPresInfo;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-09-09T19:36:59.545+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "esdk_uc_professional_server", name = "UCProfessional.Client.Personal")
@XmlSeeAlso({ObjectFactory.class})
public interface UCProfessionalClientPersonal {

    @RequestWrapper(localName = "publishPresenceInfo", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.PublishPresenceInfo")
    @WebMethod(action = "esdk_uc_professional_server.publishPresenceInfo")
    @ResponseWrapper(localName = "publishPresenceInfoResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.PublishPresenceInfoResponse")
    public void publishPresenceInfo(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "presPublish", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.PresPublishInfo presPublish,
        @WebParam(name = "expires", targetNamespace = "")
        long expires,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "resPubPresInfo", targetNamespace = "")
        javax.xml.ws.Holder<ResPubPresInfo> resPubPresInfo
    );

    @RequestWrapper(localName = "refreshSubscribePGM", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.RefreshSubscribePGM")
    @WebMethod(action = "esdk_uc_professional_server.refreshSubscribePGM")
    @ResponseWrapper(localName = "refreshSubscribePGMResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.RefreshSubscribePGMResponse")
    public void refreshSubscribePGM(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "subFlag", targetNamespace = "")
        java.lang.String subFlag,
        @WebParam(name = "groupUrl", targetNamespace = "")
        java.lang.String groupUrl,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(mode = WebParam.Mode.INOUT, name = "expires", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Long> expires,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode
    );

    @RequestWrapper(localName = "subPGM", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.SubPGM")
    @WebMethod(action = "esdk_uc_professional_server.subPGM")
    @ResponseWrapper(localName = "subPGMResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.SubPGMResponse")
    public void subPGM(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "subFlag", targetNamespace = "")
        java.lang.String subFlag,
        @WebParam(name = "groupUrl", targetNamespace = "")
        java.lang.String groupUrl,
        @WebParam(name = "creator", targetNamespace = "")
        java.lang.String creator,
        @WebParam(mode = WebParam.Mode.INOUT, name = "expires", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Long> expires,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode
    );

    @RequestWrapper(localName = "refreshPresInfo", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.RefreshPresInfo")
    @WebMethod(action = "esdk_uc_professional_server.refreshPresInfo")
    @ResponseWrapper(localName = "refreshPresInfoResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.RefreshPresInfoResponse")
    public void refreshPresInfo(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "presPublish", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.PresPublishInfo presPublish,
        @WebParam(name = "expires", targetNamespace = "")
        long expires,
        @WebParam(name = "etag", targetNamespace = "")
        java.lang.String etag,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "resPubPresInfo", targetNamespace = "")
        javax.xml.ws.Holder<ResPubPresInfo> resPubPresInfo
    );

    @RequestWrapper(localName = "uploadMobileAddress", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.UploadMobileAddress")
    @WebMethod(action = "esdk_uc_professional_server.uploadMobileAddress")
    @ResponseWrapper(localName = "uploadMobileAddressResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.UploadMobileAddressResponse")
    public void uploadMobileAddress(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "mobilePhone", targetNamespace = "")
        java.util.List<java.lang.String> mobilePhone,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "userMobile", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.huawei.esdk.uc.professional.local.bean.clientmanager.UserMobile>> userMobile
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "uploadHeadImageId", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.UploadHeadImageId")
    @WebMethod(action = "esdk_uc_professional_server.uploadHeadImageId")
    @ResponseWrapper(localName = "uploadHeadImageIdResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.UploadHeadImageIdResponse")
    public java.lang.Integer uploadHeadImageId(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "headImageId", targetNamespace = "")
        java.lang.String headImageId
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "setSignature", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.SetSignature")
    @WebMethod(action = "esdk_uc_professional_server.setSignature")
    @ResponseWrapper(localName = "setSignatureResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.SetSignatureResponse")
    public java.lang.Integer setSignature(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "userInfo", targetNamespace = "")
        java.lang.String userInfo
    );
}
