package com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-09-09T19:36:59.482+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "esdk_uc_professional_server", name = "UCProfessional.Client.MsgServer")
@XmlSeeAlso({ObjectFactory.class})
public interface UCProfessionalClientMsgServer {

    @RequestWrapper(localName = "getMsgLog", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.GetMsgLog")
    @WebMethod(action = "esdk_uc_professional_server.getMsgLog")
    @ResponseWrapper(localName = "getMsgLogResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.GetMsgLogResponse")
    public void getMsgLog(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "msgHistoryCond", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.clientmanager.MsgHistoryCondition msgHistoryCond,
        @WebParam(mode = WebParam.Mode.INOUT, name = "pageInfo", targetNamespace = "")
        javax.xml.ws.Holder<PageInfo> pageInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "msgHistoryInfo", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.huawei.esdk.uc.professional.local.bean.clientmanager.MsgHistoryInfo>> msgHistoryInfo
    );

    @RequestWrapper(localName = "getMessage", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.GetMessage")
    @WebMethod(action = "esdk_uc_professional_server.getMessage")
    @ResponseWrapper(localName = "getMessageResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.GetMessageResponse")
    public void getMessage(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "timeStamp", targetNamespace = "")
        java.util.Date timeStamp,
        @WebParam(name = "msgType", targetNamespace = "")
        java.lang.String msgType,
        @WebParam(mode = WebParam.Mode.INOUT, name = "pageInfo", targetNamespace = "")
        javax.xml.ws.Holder<PageInfo> pageInfo,
        @WebParam(mode = WebParam.Mode.OUT, name = "resultCode", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> resultCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "msgHistoryInfo", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<com.huawei.esdk.uc.professional.local.bean.clientmanager.MsgHistoryInfo>> msgHistoryInfo
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "markMsgReadFlag", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.MarkMsgReadFlag")
    @WebMethod(action = "esdk_uc_professional_server.markMsgReadFlag")
    @ResponseWrapper(localName = "markMsgReadFlagResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.MarkMsgReadFlagResponse")
    public java.lang.Integer markMsgReadFlag(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "msgHistoryCond", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.clientmanager.MsgHistoryCondition msgHistoryCond,
        @WebParam(name = "msgId", targetNamespace = "")
        java.lang.String msgId
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.SendMessage")
    @WebMethod(action = "esdk_uc_professional_server.sendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.SendMessageResponse")
    public java.lang.Integer sendMessage(
        @WebParam(name = "ucAccount", targetNamespace = "")
        java.lang.String ucAccount,
        @WebParam(name = "recvType", targetNamespace = "")
        java.lang.Integer recvType,
        @WebParam(name = "recver", targetNamespace = "")
        java.lang.String recver,
        @WebParam(name = "msg", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.clientmanager.MsgInfo msg
    );

    @WebResult(name = "resultCode", targetNamespace = "")
    @RequestWrapper(localName = "withdrawMessage", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.WithdrawMessage")
    @WebMethod(action = "esdk_uc_professional_server.withdrawMessage")
    @ResponseWrapper(localName = "withdrawMessageResponse", targetNamespace = "esdk_uc_professional_server", className = "com.huawei.esdk.uc.professional.local.impl.autogen.clientmanager.WithdrawMessageResponse")
    public java.lang.Integer withdrawMessage(
        @WebParam(name = "msgUserType", targetNamespace = "")
        java.lang.Integer msgUserType,
        @WebParam(name = "sender", targetNamespace = "")
        java.lang.String sender,
        @WebParam(name = "recver", targetNamespace = "")
        java.lang.String recver,
        @WebParam(name = "msg", targetNamespace = "")
        com.huawei.esdk.uc.professional.local.bean.clientmanager.MsgInfo msg
    );
}
