package com.huawei.esdk.uc.professional.local.impl.autogen.callback;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2013-09-30T09:21:28.134+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "esdk_uc_professional_server", name = "UCProfessional.Client")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UCProfessionalClient {

    @WebResult(name = "notifyGroupManageResponse", targetNamespace = "esdk_uc_professional_server", partName = "parameters")
    @WebMethod(action = "esdk_uc_professional_server.notifyGroupManage")
    public NotifyGroupManageResponse notifyGroupManage(
        @WebParam(partName = "parameters", name = "notifyGroupManage", targetNamespace = "esdk_uc_professional_server")
        NotifyGroupManage parameters
    );

    @WebResult(name = "notifyMessageResponse", targetNamespace = "esdk_uc_professional_server", partName = "parameters")
    @WebMethod(action = "esdk_uc_professional_server.notifyMessage")
    public NotifyMessageResponse notifyMessage(
        @WebParam(partName = "parameters", name = "notifyMessage", targetNamespace = "esdk_uc_professional_server")
        NotifyMessage parameters
    );

    @WebResult(name = "notifyFriendPresInfoResponse", targetNamespace = "esdk_uc_professional_server", partName = "parameters")
    @WebMethod(action = "esdk_uc_professional_server.notifyFriendPresInfo")
    public NotifyFriendPresInfoResponse notifyFriendPresInfo(
        @WebParam(partName = "parameters", name = "notifyFriendPresInfo", targetNamespace = "esdk_uc_professional_server")
        NotifyFriendPresInfo parameters
    );

    @WebResult(name = "notifyClientRegisterStatusResponse", targetNamespace = "esdk_uc_professional_server", partName = "parameters")
    @WebMethod(action = "esdk_uc_professional_server.notifyClientRegisterStatus")
    public NotifyClientRegisterStatusResponse notifyClientRegisterStatus(
        @WebParam(partName = "parameters", name = "notifyClientRegisterStatus", targetNamespace = "esdk_uc_professional_server")
        NotifyClientRegisterStatus parameters
    );
}
